name: Publish
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install pnpm
        run: npm i -g pnpm@8 --force

      - name: install packages
        run: pnpm install

      - name: check types
        run: pnpm check-ts

      - name: build
        run: pnpm build -- --production

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_SECRET }}
          package: ./dist/package.json
