name: Publish
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - uses: actions/checkout@v2

      - name: install packages
        run: npm install

      - name: check types
        run: npm run check-ts

      - name: build
        run: npm run build --production

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_SECRET }}
          package: ./dist/package.json
